library(shiny)
library(shinycssloaders)
library(DT)

# Define UI for Python 2 example app ----
ui <- fluidPage(
  
  # App title ----
  titlePanel('Reticulated app example'),
  
  # Sidebar layout with input and output definitions ----
  sidebarLayout(
    
    # Sidebar panel for inputs ----
    sidebarPanel(
      
      h4('Inputs to native R functions'),
      
      # Input: Select the random distribution type ----
      radioButtons('dist', 
                   'Distribution type:',
                   choices = c('Normal' = 'norm',
                               'Uniform' = 'unif', 
                               'Log-normal' = 'lnorm', 
                               'Exponential' = 'exp')),
      br(),
      
      # Input: Slider for the number of observations to generate ----
      sliderInput('n',
                  'Number of observations:',
                  value = 5000,
                  min = 100,
                  max = 10000),
      hr(),
      h4('Inputs to Python functions called by R'),
      
      # Input: Text that will be passed to a Python function ----
      textInput('str',
                'Text to display',
                value = 'This text is being printed by a Python function!'),
      
      # Input: Numbers that will be passed to a Python function ----
      numericInput('x',
                   'x value',
                   value = 2),
      numericInput('y',
                   'y value',
                   value = 2)
      
    ),
    
    # Main panel for displaying outputs ----
    mainPanel(
      
      # Output: Tabset w/ plot, summary, and table ----
      tabsetPanel(type = 'tabs',
                  tabPanel('Demo', 
                           br(),
                           h3('Outputs generated with native R'),
                           br(),
                           withSpinner(plotOutput('plot')),
                           br(),
                           h3('Outputs generated by Python functions called by R'),
                           verbatimTextOutput('message'),
                           br(),
                           'Use the numpy Python package to add two numbers',
                           verbatimTextOutput('xy')),
                  tabPanel('Architecture Info', 
                           h3('Current architecture info'),
                           '(These values will change when app is run locally vs on Shinyapps.io)',
                           hr(),
                           withSpinner(DT::dataTableOutput('sysinfo')),
                           br(),
                           verbatimTextOutput('python_version'),
                           verbatimTextOutput('rsconnect_opt'),
                           verbatimTextOutput('ret_env_var'),
                           verbatimTextOutput('ret_env'),
                           verbatimTextOutput('path'))
      )
      
    )
  )
)